#!/usr/bin/env python

import rospy
from std_msgs.msg import String

def node1():
    message_pub = rospy.Publisher("/hello", String, queue_size=10)
    rospy.init_node('node1')
    mymessage = String()
    mymessage.data = "hello"
    rate = rospy.Rate(10)

    while not rospy.is_shutdown():
        message_pub.publish(mymessage)
        rate.sleep()

if __name__ == '__main__':
    try:
        node1()
    except rospy.ROSInterruptException:
        pass