#!/usr/bin/env python

import sys
import rospy
from geometry_msgs.msg import Twist


def turtle_circle(radius):
    pub = rospy.Publisher('/turtle1', Twist, queue_size=10)
    rospy.init_node('turtlesim', anonymous=True)
    rate = rospy.Rate(0.5)
    vel = Twist()
    while not rospy.is_shutdown():
        vel.linear.x = radius
        vel.linear.y = 0
        vel.linear.z = 0
        vel.angular.x = 0
        vel.angular.y = 0
        vel.angular.z = 1
        rospy.loginfo("Radius = %f", radius)
        pub.publish(vel)
        rate.sleep()


if __name__ == '__main__':
    try:
        turtle_circle(float(sys.argv[1]))
    except rospy.ROSInterruptException:
        pass
