#!/usr/bin/env python

from __future__ import print_function

import sys
import rospy
from std_msgs.msg import String
from geometry_msgs.msg import Twist
from assign.srv import *

radius = 5


def listen1(data):
    global radius
    radius = int(data.data)
    print(data.data)
    print((getangvel(radius)))
    move(radius)


def listener():
    rospy.init_node('listener')
    rospy.Subscriber("/radius", String, listen1)
    rospy.spin()


def getangvel(radius):
    rospy.wait_for_service('service_ang_vel')
    try:
        angvel = rospy.ServiceProxy('service_ang_vel', service2)
        resp2 = angvel(int(radius))
        return resp2.angular_velocity
    except rospy.ServiceException as e:
        print("Service call failed: %s" % e)


pub = rospy.Publisher('/cmd_vel', Twist, queue_size=1)


def move(radius):
    move = Twist()
    move.linear.x = 0.1
    move.angular.z = getangvel(radius)


if __name__ == '__main__':
    listener()
