#!/usr/bin/env python

from __future__ import print_function
from assign.srv import service2,service2Response
import rospy

linear_velocity=0.1

def handle_req(req):
    print("Returning [%s/%s]"%(linear_velocity,req.rad))
    resp2=service2Response()
    resp2.angular_velocity=linear_velocity/req.rad
    return resp2.angular_velocity

def angular_vel_server():
    rospy.init_node('service_ang_vel_node')
    s = rospy.Service('service_ang_vel', service2, handle_req)
    print("Ready to give angular velocity")
    rospy.spin()

if __name__ == "__main__":
    angular_vel_server()